import enum


class ApplicationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    PROCESSING = "PROCESSING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISBURSED = "DISBURSED"


class DocumentType(str, enum.Enum):
    IDENTITY = "IDENTITY"
    INCOME = "INCOME"
    BANK_STATEMENT = "BANK_STATEMENT"
    APPLICATION_FORM = "APPLICATION_FORM"
    OTHER = "OTHER"
